### ISSUE TITLE
ETN mystery tags layer - add tag code space

### ISSUE THREAD

**Issue by diniangela** [lifewatch/etn-otn-exchange#17]
To start looking at cross matching between ETN detections and OTN tags, I've started comparing OTN tags against the ETN mystery tag layer. However, this is a bit difficult because the ETN mystery tag Geoserver layer only shows the tag id code, is it possible to add the tag code space to this layer?

@jdpye @naomitress

**Comment by aubrivliz** [comment]
The problem here is that some detection files only registerred the tag id code. This has been fixed by the manufacturer but the detections with only the id code cannot be transformed to the tag full id. 

I think it is best to take a look to the data and find a solution for this.

**Comment by jdpye** [comment]
No, the default output only gives the tag ID and the year of detection. the OTN sided one adds the ocean region to improve the researcher's ability to decide whether it is their tag or not, but mystery tag tables don't give receiver positions, so that we can incentivize that tags are registered before matches get made by any individiuals who already have the tag metadata.

**Comment by Tjess** [comment]
Ok, no position.
We can give region based on Marine Regions.

Verzonden vanaf mijn Galaxy



-------- Oorspronkelijk bericht --------
Van: Jon Pye ***@***.***>
Datum: 2/06/22 18:50 (GMT+01:00)
Aan: lifewatch/etn-otn-exchange ***@***.***>
Cc: Francisco Hernandez ***@***.***>, Comment ***@***.***>
Onderwerp: Re: [lifewatch/etn-otn-exchange] ETN mystery tags layer - add tag code space (Issue #17)


No, the default output only gives the tag ID and the year of detection. the OTN sided one adds the ocean region to improve the researcher's ability to decide whether it is their tag or not, but mystery tag tables don't give receiver positions, so that we can incentivize that tags are registered before matches get made by any individiuals who already have the tag metadata.

**Comment by Tjess** [comment]
Lets do that, then.
We have everything in house.





Verzonden vanaf mijn Galaxy



-------- Oorspronkelijk bericht --------
Van: Angela Dini ***@***.***>
Datum: 2/06/22 19:31 (GMT+01:00)
Aan: lifewatch/etn-otn-exchange ***@***.***>
Cc: Francisco Hernandez ***@***.***>, Comment ***@***.***>
Onderwerp: Re: [lifewatch/etn-otn-exchange] ETN mystery tags layer - add tag code space (Issue #17)


The region based on Marine Regions sounds good! We can pull the geometric information from Marine Regions for researchers if you wanted to include the Marine Regions ID in a column in the mystery tags layer

**Comment by diniangela** [comment]
Ok great! Please let me know when it's ready and I'll re-pull down the mystery tags layer

**Comment by aubrivliz** [comment]
I've updated the layer with marine Regions.

Data example:

`{"id":1,"transmitter":"A69-9007-9989","det_year":2022,"region":"Balearic (Iberian Sea)"}`

**Comment by diniangela** [comment]
Looking more at the mystery tag layer more, we see the det count has been removed but it would be great to be able to provide this to researchers.

It would be great  to have a similar format to the OTN mystery tag layer:
- collectioncode (if possible)
- yearcollected
- transmitter
- region (can be IMIS ID if that would be easier to populate)
- det_count

Please let us know if this is possible

**Comment by aubrivliz** [comment]
@diniangela The layer has been updated to the OTN mystery format.

**Comment by diniangela** [comment]
@aubrivliz we were checking out the regions field in the mystery tags layer and saw that some were null. We’re using this field to help the researchers decide if the matches between the detections and tags are false matches or not. If these values are null, what should we use instead, or would you prefer it to remain null if it’s null in the mystery tags layer?
we could also potentially grab it from the project metadata, which field would be ok to use from the project metadata? GeoTerm in the JSON?
