### ISSUE TITLE
Grabbing ETN detections process

### ISSUE THREAD

**Issue by diniangela** [lifewatch/etn-otn-exchange#19]
I noticed if the ETN detections are grabbed from Geoserver CSV's, they only only show 1 million of the detections. I have been trying pagination with WFS but it has proven to be more difficult than I initially thought.

Is there a better way to grab the ETN detections from ETN in their entirety?

@jdpye @naomitress

**Comment by aubrivliz** [comment]
Hi angela, the best way to do this is indeed with the WFS geoJSON format and use the paging. It is some coding work but feasible.

**Comment by jdpye** [comment]
Looks like there's a # of queries limit on the GeoServer. Could be there's something default being set in this way: https://docs.geoserver.org/latest/en/user/extensions/controlflow/index.html#per-user-rate-control but if it's something else, we'd still need to lift it in order to do ~550 queries every time we do a detections cross-match.

**Comment by jdpye** [comment]
I was able to grab 150m or so detections over 150 queries yesterday, haven't checked over them but after 150m i got a 0-byte return from the GeoServer, which may mean i had run out of pages, or may mean that i hit the rate-limit block.
