### ISSUE TITLE
Modified  datetime on project level

### ISSUE THREAD

**Issue by aubrivliz** [lifewatch/etn-otn-exchange#31]
On the OTN project layer there will be a new field "datelastmodified " to check if there is any data change happend during the last push for a speicifc project. 

- [x] Create new field in the database and add it to the layer "etn_projects"

**Comment by jdpye** [comment]
I suspect we'll call it `datelastmodified` if only because that's what we've called it elsewhere in the past. But it will be a date field, or possibly a datetime field, with the maximum value of the `datelastmodified` fields for a project's components (station records, animal releases, download events, etc) to indicate that there has been new or modified data within that project.
